- !!eu.fp7.scase.inputParser.YamlResource
  Name: gift
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: nameofbook
    Type: String
    Unique: true
    NamingProperty: false
  - Name: descriptionofevent
    Type: String
    Unique: true
    NamingProperty: false
  - Name: eventstart
    Type: String
    Unique: true
    NamingProperty: false
  - Name: nameofmovie
    Type: String
    Unique: true
    NamingProperty: false
  - Name: bookpublisher
    Type: String
    Unique: true
    NamingProperty: false
  - Name: eventcountry
    Type: String
    Unique: true
    NamingProperty: false
  - Name: priceofbook
    Type: String
    Unique: true
    NamingProperty: false
  - Name: conditionofmovie
    Type: String
    Unique: true
    NamingProperty: false
  - Name: bookauthor
    Type: String
    Unique: true
    NamingProperty: false
  - Name: descriptionofmusic
    Type: String
    Unique: true
    NamingProperty: false
  - Name: bookpage
    Type: String
    Unique: true
    NamingProperty: false
  - Name: eventcity
    Type: String
    Unique: true
    NamingProperty: false
  - Name: priceofmusic
    Type: String
    Unique: true
    NamingProperty: false
  - Name: nameofevent
    Type: String
    Unique: true
    NamingProperty: false
  - Name: recipient
    Type: String
    Unique: true
    NamingProperty: false
  - Name: conditionofmusic
    Type: String
    Unique: true
    NamingProperty: false
  - Name: descriptionofmovie
    Type: String
    Unique: true
    NamingProperty: false
  - Name: sender
    Type: String
    Unique: true
    NamingProperty: false
  - Name: imageofevent
    Type: String
    Unique: true
    NamingProperty: false
  - Name: nameofmusic
    Type: String
    Unique: true
    NamingProperty: false
  - Name: imageofbook
    Type: String
    Unique: true
    NamingProperty: false
  - Name: imageofmovie
    Type: String
    Unique: true
    NamingProperty: false
  - Name: priceofevent
    Type: String
    Unique: true
    NamingProperty: false
  - Name: priceofmovie
    Type: String
    Unique: true
    NamingProperty: false
  - Name: imageofmusic
    Type: String
    Unique: true
    NamingProperty: false
  - Name: bookcategory
    Type: String
    Unique: true
    NamingProperty: false
  - Name: sent
    Type: String
    Unique: true
    NamingProperty: false
  - Name: received
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: [category, giftApprove, giftDecline, giftBuy]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: giftApprove
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: giftDecline
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: giftBuy
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: logout
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [logoutLogout]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: logoutLogout
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: username
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [usernameLogin]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: usernameLogin
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: category
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: type
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: [categorySelect, gift]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: categorySelect
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: account
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read, Create]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: lastName
    Type: String
    Unique: true
    NamingProperty: false
  - Name: email
    Type: String
    Unique: true
    NamingProperty: false
  - Name: firstName
    Type: String
    Unique: true
    NamingProperty: false
  - Name: password
    Type: String
    Unique: true
    NamingProperty: false
  - Name: location
    Type: String
    Unique: true
    NamingProperty: false
  - Name: username
    Type: String
    Unique: true
    NamingProperty: false
  - Name: hometown
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: friend
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [category, logout]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: password
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [passwordLogin]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: passwordLogin
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: login
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: username
    Type: String
    Unique: true
    NamingProperty: false
  - Name: password
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: [loginLogin, friend]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: loginLogin
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

