- !!eu.fp7.scase.inputParser.YamlResource
  Name: gift
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Create, Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: sender
    Type: String
    Unique: true
    NamingProperty: false
  - Name: recipient
    Type: String
    Unique: true
    NamingProperty: false
  - Name: startOfEvent
    Type: String
    Unique: true
    NamingProperty: false
  - Name: publisher
    Type: String
    Unique: true
    NamingProperty: false
  - Name: name
    Type: String
    Unique: true
    NamingProperty: false
  - Name: condition
    Type: String
    Unique: true
    NamingProperty: false
  - Name: price
    Type: String
    Unique: true
    NamingProperty: false
  - Name: author
    Type: String
    Unique: true
    NamingProperty: false
  - Name: pageCount
    Type: String
    Unique: true
    NamingProperty: false
  - Name: categoryType
    Type: String
    Unique: true
    NamingProperty: false
  - Name: description
    Type: String
    Unique: true
    NamingProperty: false
  - Name: image
    Type: String
    Unique: true
    NamingProperty: false
  - Name: categoryOfBook
    Type: String
    Unique: true
    NamingProperty: false
  - Name: location
    Type: String
    Unique: true
    NamingProperty: false
  - Name: sent
    Type: String
    Unique: true
    NamingProperty: false
  - Name: received
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: [category, giftBuy]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: giftBuy
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: logout
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [logoutLogout]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: logoutLogout
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: type
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: book
    Type: String
    Unique: true
    NamingProperty: false
  - Name: movy
    Type: String
    Unique: true
    NamingProperty: false
  - Name: music
    Type: String
    Unique: true
    NamingProperty: false
  - Name: event
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: [category]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: username
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [usernameLogin]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: usernameLogin
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: lastName
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [account]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: friend
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [friendSelect, category, logout]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: friendSelect
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: firstName
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [account]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: category
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: book
    Type: String
    Unique: true
    NamingProperty: false
  - Name: name
    Type: String
    Unique: true
    NamingProperty: false
  - Name: music
    Type: String
    Unique: true
    NamingProperty: false
  - Name: movy
    Type: String
    Unique: true
    NamingProperty: false
  - Name: event
    Type: String
    Unique: true
    NamingProperty: false
  - Name: type
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: [categoryBe, gift, categorySelect]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: categoryBe
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: categorySelect
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: email
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [account]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: account
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Update, Read, Create]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: lastName
    Type: String
    Unique: true
    NamingProperty: false
  - Name: email
    Type: String
    Unique: true
    NamingProperty: false
  - Name: firstName
    Type: String
    Unique: true
    NamingProperty: false
  - Name: password
    Type: String
    Unique: true
    NamingProperty: false
  - Name: location
    Type: String
    Unique: true
    NamingProperty: false
  - Name: username
    Type: String
    Unique: true
    NamingProperty: false
  - Name: hometown
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: hometown
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [account]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: application
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [applicationLogout]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: applicationLogout
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: password
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [passwordLogin]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: passwordLogin
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: location
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [account]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: login
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: username
    Type: String
    Unique: true
    NamingProperty: false
  - Name: password
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: [loginLogin, friend]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: loginLogin
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

