- !!eu.fp7.scase.inputParser.YamlResource
  Name: gift
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: received
    Type: String
    Unique: true
    NamingProperty: false
  - Name: sent
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: [category, giftBuy, giftApprove, giftDecline]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: giftBuy
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: giftApprove
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: giftDecline
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: username
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [usernameLogin]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: usernameLogin
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: category
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: type
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: account
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Create]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties:
  - Name: lastName
    Type: String
    Unique: true
    NamingProperty: false
  - Name: email
    Type: String
    Unique: true
    NamingProperty: false
  - Name: firstName
    Type: String
    Unique: true
    NamingProperty: false
  - Name: password
    Type: String
    Unique: true
    NamingProperty: false
  - Name: location
    Type: String
    Unique: true
    NamingProperty: false
  - Name: username
    Type: String
    Unique: true
    NamingProperty: false
  - Name: hometown
    Type: String
    Unique: true
    NamingProperty: false
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: friend
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: [Read]
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: application
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [applicationLogout]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: applicationLogout
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

- !!eu.fp7.scase.inputParser.YamlResource
  Name: password
  IsAlgorithmic: false
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: [passwordLogin]

- !!eu.fp7.scase.inputParser.YamlResource
  Name: passwordLogin
  IsAlgorithmic: true
  IsExternalService: false
  CRUDActivities: []
  InputRepresentation: JSON
  OutputRepresentation: JSON
  Properties: []
  RelatedResources: []

